version: '3.8'
services:

  #
  # A JDBC data source for user and client storage, to enable GraphQL access
  #
  curity-data:
    image: postgres:15.3
    hostname: dbserver
    container_name: postgres
    ports:
     - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'


  #
  # A standalone instance of the Curity Identity Server that uses a Postgres database
  # Ensure that the latest local copy of the Docker image is 8.4 or above
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    hostname: curityserver
    container_name: curity
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./config-backup.xml:/opt/idsvr/etc/init/config.xml
     - ./license.json:/opt/idsvr/etc/init/license/license.json
    environment:
      ADMIN: 'true'
      ADMIN_UI_HTTP_MODE: 'true'
      ADMIN_PASSWORD: 'Password1'
      LOGGING_LEVEL: 'INFO'
      RUNTIME_BASE_URL: "${RUNTIME_BASE_URL}"
      ADMIN_BASE_URL: "${ADMIN_BASE_URL}"
